micronaut:
  application:
    name: msAlumno
  server:
    port: ${ALUMNO_PORT:0}
datasources:
  default:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5435}/alumnoDB
    driverClassName: org.postgresql.Driver
    username: ${ALUMNO_USER:postgres}
    password: ${ALUMNO_PASSWORD:kasparov}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
netty:
  default:
    allocator:
      max-order: 3
eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}