package com.lucho.ms.util;

public enum ErrorCode {

	  	URL_INVALIDA,
	    ERROR_INTERNO_DEL_SERVIDOR,
	    BODY_REQUEST_MAL_FORMADO,
	    QUERY_PARAM_INVALIDO,
	    RECURSO_NO_ENCONTRADO,
	    ERROR_DE_VALIDACION,
	    RESPUESTA_ERROR,
	    CONSULTA_INVALIDA,
	    OPERACION_INVALIDA,
	    CREDENCIALES_INVALIDAS,
	    ACCESS_TOKEN_INVALIDO,
	    REFRESH_TOKEN_INVALIDO,
	    RECURSO_NO_AUTORIZADO,
	    RECURSO_EN_USO,
	    ERROR_COMUNICACION_EXTERNA;
}
